import AppQueryClientProvider from "@/components/AppQueryClientProvider";
import StyledComponentsRegistry from "@/components/StyledComponentsRegistry";
import { ConfigProvider } from "antd";
import antPtBr from 'antd/locale/pt_BR';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Reserva de Salas",
  description: "Generated by create next app",
};

const theme = {
  token: {
    colorLink: "var(--color-gray-dark)",
    colorLinkHover: "var(--color-orange)",
    colorLinkActive: "var(--color-orange)"
  },
  components: {
    Menu: {
      itemColor: "var(--color-gray-dark)",
      itemSelectedColor: "var(--color-orange)",
      itemSelectedBg: "var(--color-orange-lighter)",
    },
    Layout: {
      siderBg: "var(--color-secondary)"
    },
    Button: {
      defaultHoverBg: "var(--color-orange)",
      defaultBg: "var(--color-orange)",
      defaultColor: "var(--color-secondary)",
      defaultHoverColor: "var(--color-secondary)",
      defaultHoverBorderColor: "var(--color-orange)",
      defaultActiveColor: "var(--color-orange)",
      defaultActiveBorderColor: "var(--color-orange)",
    },
    Calendar: {
      colorBgContainer: "var(--color-primary)",
      colorBgHeader: "var(--color-primary)",
      colorFillSecondary: "var(--color-primary)",
      itemActiveBg: "var(--color-secondary)",
      colorPrimary: "var(--color-orange)",
      paddingXXS: 0,
      paddingXS: 0,
    },
    Select: {
      itemActiveBg: "var(--color-orange-lighter)",
      colorPrimary: "var(--color-orange)",
      colorPrimaryHover: "var(--color-orange)",
      optionSelectedBg: "var(--color-gray)",
    },
    Radio: {
      colorPrimary: "var(--color-orange)",
      colorPrimaryActive: "var(--color-orange)",
      colorPrimaryBorder: "var(--color-orange)",
      colorPrimaryHover: "var(--color-orange)",
    },
    Card: {
      colorPrimary: "var(--color-orange)"
    },
    Input: {
      activeBorderColor: "var(--color-orange)",
      hoverBorderColor: "var(--color-orange)",
    },
    DatePicker: {
      activeBorderColor: "var(--color-orange)",
      hoverBorderColor: "var(--color-orange)",
    },
    InputNumber: {
      activeBorderColor: "var(--color-orange)",
      hoverBorderColor: "var(--color-orange)",
    },
    TimePicker: {
      activeBorderColor: "var(--color-orange)",
      hoverBorderColor: "var(--color-orange)",
    },
  }
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>
        <ConfigProvider locale={antPtBr} theme={theme}>
          <StyledComponentsRegistry>
            <AppQueryClientProvider>
              {children} 
            </AppQueryClientProvider>
          </StyledComponentsRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
